### ISSUE TITLE
ERROR: Failed to resolve: :typingdnarecordermobile:

### ISSUE THREAD

**Issue by Kostya1375** [TypingDNA/TypingDNARecorder-Android#1]
Trying to add library in manual mode. All that I get it this error:
`ERROR: Failed to resolve: :typingdnarecordermobile:`

**Comment by dannoane** [comment]
Hello @Kostya1375 

I uploaded a new build of the library, and everything should be working now. The recorder is now under `com.typingdna.typingdnarecorderandroid.*`.
Let me know if there are any problems.

**Comment by Kostya1375** [comment]
Thank you! It can be installed but only in "auto" mode
